apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    {{- include "apache-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "apache-stack.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort}}
      {{- end }}